# yaml-language-server: $schema=https://taskfile.dev/schema.json

version: '3'

vars:
  APP: cooking

tasks:
  start-image-local:
    desc: Start cooking locally
    preconditions:
      - sh: podman network exists {{.APP}}-net
        msg: "Create podman network using: podman network create {{.APP}}-net"
    cmds:
      - CGO_ENABLED=0 GOARCH=amd64 GOOS=linux go build -o build/{{.APP}}.linux
      - podman build . -t {{.APP}}
      - podman run --name {{.APP}} -d --replace --network {{.APP}}-net localhost/{{.APP}}
      - podman network disconnect cooking-net proxy
      - podman network connect cooking-net proxy

  connect-local:
    cmds:
      - podman exec -it {{.APP}} /bin/busybox /bin/sh
