#!/usr/bin/perl

package extension;

use utf8;
use Encode 'decode';
use CGI::Carp qw(fatalsToBrowser);
use CGI qw/:standard :netscape/;

use strict;

my $dir = "../recbook";

my $searchstring = decode("utf8", param('q'));

sub main
{
	$searchstring = lc($searchstring);
	my $out = "<p>Поиск: ".$searchstring."</p>";
	$out .= "<p class=\"left\">".searchdir()."</p>";
	return $out;
}

sub searchdir
{
	my ($relpath) = @_;
	my $out = "";
	my $path = $dir."/".$relpath;
	opendir(DIR, $path);
	my @files = grep { /\.html$/ && -f "$path/$_" && !/^_/} readdir(DIR);
	closedir DIR;
	my @linkfiles = @files;
	@files = map { $_ = "$path/$_" } @files;
	closedir(DIR);
	
#	$out .= $path."<br>";
	
	for (my $i = 0; $i < @files; $i++)
	{
#		$out .= @files[$i]."<br>";
		open FILE, "<:utf8", @files[$i];
		my $title = <FILE>;
		my $text = join '', <FILE>;
		close FILE;

		$text =~ s/\<.*?\>//g;
		$title =~ s/\<.*?\>//g;
		
		if ( $text =~ m/$searchstring/si || $title =~ m/$searchstring/si )
		{
			$out .= qq!<a href="$relpath#@linkfiles[$i]">$title</a><br>\n!;
		}
	}
	
	opendir(DIR, $path);
	my @subdirs = grep { -d "$path/$_" && !/^_/ && !/\./} readdir(DIR);
	closedir(DIR);

	foreach (@subdirs)
	{
		$out .= &searchdir("$relpath/$_");
	}
	
	
	return $out;
}
